In [1]:
import pandas as pd
import geopandas as gpd
import psycopg2
from sqlalchemy import create_engine
import folium
from branca.colormap import linear

In [2]:
def fetch_gdf(sql, dbname):
    db_url = f"postgresql://postgres:postgres@postgis_container:5432/{dbname}"
    engine = create_engine(db_url)
    return gpd.read_postgis(sql, engine, geom_col="geom")

In [5]:
sql = """
WITH pop19 AS (
    SELECT
        m.name AS mesh_id,
        d.population,
        m.geom
    FROM pop d
    JOIN pop_mesh m
      ON d.mesh1kmid = m.name
    WHERE
        d.year = '2019'
        AND d.month = '04'
        AND d.dayflag = '0'
        AND d.timezone = '0'
)
SELECT
    a.name_2 AS municipality,
    SUM(pop19.population) AS population,
    a.geom
FROM pop19
JOIN adm2 a
  ON ST_Within(pop19.geom, a.geom)
WHERE a.name_1 = 'Tokyo'
GROUP BY a.name_2, a.geom
"""

gdf = fetch_gdf(sql, "gisdb")
gdf.head()

  municipality  population                                               geom
0       Adachi    382719.0  MULTIPOLYGON (((139.76427 35.75556, 139.76257 ...
1      Akiruno     47338.0  MULTIPOLYGON (((139.3362 35.70942, 139.33572 3...
2     Akishima     70209.0  MULTIPOLYGON (((139.37921 35.68805, 139.35854 ...
3      Arakawa     35291.0  MULTIPOLYGON (((139.82095 35.73718, 139.8186 3...
4       Bunkyō    169405.0  MULTIPOLYGON (((139.78056 35.70245, 139.77692 ...

In [6]:
gdf = gdf.to_crs(epsg=6677)

gdf["area_km2"] = gdf.area / 1_000_000

gdf["density"] = gdf["population"] / gdf["area_km2"]

gdf[["municipality", "population", "area_km2", "density"]].head()

  municipality  population   area_km2       density
0       Adachi    382719.0  48.757998   7849.358361
1      Akiruno     47338.0  77.830668    608.217828
2     Akishima     70209.0  18.141293   3870.120963
3      Arakawa     35291.0   9.275198   3804.878525
4       Bunkyō    169405.0  11.537263  14683.292195

In [7]:
gdf = gdf.to_crs(epsg=4326)

In [10]:
colormap = linear.YlOrRd_09.scale(
    gdf["density"].min(),
    gdf["density"].max()
)
colormap.caption = "人口密度(人/km^2)"

In [11]:
m = folium.Map(location=[35.68, 139.76], zoom_start=9)

folium.GeoJson(
    gdf,
    style_function=lambda f: {
        "fillColor": colormap(f["properties"]["density"]),
        "fillOpacity": 0.7,
        "weight": 0.5,
        "color": "black"
    },
    tooltip = folium.GeoJsonTooltip(
        fields = ["municipality", "population", "density"],
        aliases = ["市区町村", "人口", "人口密度(人/km^2)"],
        localize = True
    )
).add_to(m)
m