In [1]:
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine
import folium
from branca.colormap import linear

In [2]:
def fetch_gdf(sql, dbname):
    db_url = f"postgresql://postgres:postgres@postgis_container:5432/{dbname}"
    engine = create_engine(db_url)
    return gpd.read_postgis(sql, engine, geom_col="geom")

In [4]:
sql = """
WITH pop19 AS (
    SELECT
        m.name AS mesh_id,
        d.population,
        m.geom
    FROM pop d
    JOIN pop_mesh m
      ON d.mesh1kmid = m.name
    WHERE
        d.year = '2019'
        AND d.month = '04'
        AND d.dayflag = '0'
        AND d.timezone = '0'
)
SELECT
    a.name_1 AS prefecture,
    a.name_2 AS municipality,
    SUM(pop19.population) AS population,
    a.geom
FROM pop19
JOIN adm2 a
  ON ST_Within(pop19.geom, a.geom)
WHERE a.name_1 IN (
    'Tokyo',
    'Gunma',
    'Tochigi',
    'Ibaraki',
    'Chiba',
    'Saitama',
    'Kanagawa'
)
GROUP BY a.name_1, a.name_2, a.geom
"""

gdf = fetch_gdf(sql, "gisdb")
gdf.head()

,prefecture,municipality,population,geom
0,Chiba,Abiko,75768.0,"MULTIPOLYGON (((140.1181 35.83988, 140.11653 3..."
1,Chiba,Asahi,52463.0,"MULTIPOLYGON (((140.75314 35.69377, 140.75269 ..."
2,Chiba,Chiba,781288.0,"MULTIPOLYGON (((140.29372 35.56995, 140.29419 ..."
3,Chiba,Chōnan,7421.0,"MULTIPOLYGON (((140.25267 35.32362, 140.24812 ..."
4,Chiba,Chōsei,6864.0,"MULTIPOLYGON (((140.39139 35.38525, 140.38553 ..."

In [5]:
gdf = gdf.to_crs(epsg = 6677)

gdf["area_km2"] = gdf.area / 1_000_000

gdf["density"] = gdf["population"] / gdf["area_km2"]

gdf[["prefecture", "municipality", "population", "area_km2", "density"]].head()

  prefecture municipality  population    area_km2      density
0      Chiba        Abiko     75768.0   49.179632  1540.637801
1      Chiba        Asahi     52463.0  124.384651   421.780338
2      Chiba        Chiba    781288.0  275.106894  2839.943371
3      Chiba       Chōnan      7421.0   64.310884   115.392598
4      Chiba       Chōsei      6864.0   28.344812   242.160715

In [6]:
gdf = gdf.to_crs(epsg = 4326)

In [7]:
colormap = linear.YlOrRd_09.scale(
    gdf["density"].min(),
    gdf["density"].max()
)
colormap.caption = "人口密度(人/km^2)"

In [8]:
m = folium.Map(location = [35.8, 139.6], zoom_start = 8)

folium.GeoJson(
    gdf,
    style_function = lambda f: {
        "fillColor": colormap(f["properties"]["density"]),
        "fillOpacity": 0.7,
        "weight": 0.4,
        "color": "black"
    },
    tooltip = folium.GeoJsonTooltip(
        fields = ["prefecture", "municipality", "population", "density"],
        aliases = ["都県", "市区町村", "人口", "人口密度(人/km^2)"],
        localsize = True
    )
).add_to(m)

colormap.add_to(m)
m